# Generated by Django 2.2 on 2022-01-10 13:48
import datetime

import pytz
from django.contrib.auth.models import User
from django.db import migrations
from django.db.transaction import atomic


@atomic
def create_admin(apps, schema_editor):
    admin = User.objects.filter(username='admin').first()
    if admin:
        return
    superuser = User()
    superuser.is_active = True
    superuser.is_superuser = True
    superuser.is_staff = True
    superuser.username = 'admin'
    superuser.email = 'admin@gmail.com'
    superuser.set_password(raw_password='devpass')
    superuser.last_login = datetime.datetime.now(tz=pytz.UTC)
    superuser.save()


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.RunPython(create_admin, migrations.RunPython.noop),
    ]
